name: Website Builder

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
concurrency: website-build

# Run this workflow every time a new commit is pushed to the master branch
# in the website directory, or the website build directory. 
# And also periodically, to pick up any other updates that may have occurred - 
# e.g. in the data repository or the javascript libraries
on: 
  push:
    branches:
      - master
    path:
      - websites/**
      - build/website/**
  schedule:
    # Run on a Thursday(4) at 1pm to make sure everything is up to date for the coming weekend
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 13 * * 4'
  # Allow it to be run manually - useful for testing, or pushing a out-of-cycle update
  workflow_dispatch:


jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  website-builder:
    # Name the Job
    name: Build the website from this repository
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Get the submodules as well
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      # Prepare the website directory
      - name: Copy dependencies to Website directory
        run: |
          echo `pwd`
          bash ./build/website/copy-assets.sh
        shell: bash

      # Standard usage of the plugin as described on https://jekyllrb.com/docs/continuous-integration/github-actions/
      # on 2021-01-31
      # https://github.com/marketplace/actions/jekyll-actions
      - name: Build the Jekyll site
        uses:  helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_src: 'website'
          jekyll_env: production
          # For now, lets make it push to the main repository, and see if that works,
          # we can dev dev builds working later
          target_branch: gh-pages
          # build_only: true # Delegate pushing of the built site the subsquent step so that we can direct which repo it goes to
